<?php

use Drupal\Core\Form\FormStateInterface;
//use Drupal\Core\Session\AccountInterface;

const NLP_MODULE = 'nlpservices';

const NLP_ADMIN_ROLE_ID = 'nlp_admin';
const NLP_COORDINATOR_ROLE_ID = 'nlp_coordinator';
const NLP_LEADER_ROLE_ID = 'nlp_leader';

const NLP_COORDINATOR_ROLE_LABEL = 'NLP Coordinator';
const NLP_LEADER_ROLE_LABEL = 'NLP Leader';

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Implements hook_mail_alter
 *
 * Implements hook mail alter.  For NLP messages add the signature line and
 * set the language.   For email t deliver a turf, add the information to
 * notify the sender if the email is non-deliverable.
 *
 * @param $message
 * @noinspection PhpUnused
 */
function nlpservices_mail_alter(&$message) {
  switch ($message['module']) {
    case NLP_MODULE:
      //nlp_debug_msg('$message',$message);
      if (isset($message['params']['func'])) {
        if($message['params']['func'] == 'deliver_turf' OR
          $message['params']['func'] == 'account_reminder')  {
          $params = $message['params'];
          $notify = [
            'sender' => [
              'county' => $params['county'],
              'firstName' => $params['sender']['firstName'],
              'lastName' => $params['sender']['lastName'],
              'email' => $params['sender']['email'],
            ],
            'recipient' => [
              'firstName' => $params['recipient']['firstName'],
              'lastName' => $params['recipient']['lastName'],
              'email' => $params['recipient']['email'],
            ],
          ];
          $notify_str = json_encode($notify).'<eor>';
          $message['headers']['x-nlpservices-notify'] = $notify_str;
          //$message['headers']['Reply-To'] = $params['replyTo'];
        }
      }
      $message['headers']['List-Unsubscribe'] =
        "<mailto: notifications@nlpservices.org?subject=unsubscribe>";
      break;
    case 'user':
      //nlp_debug_msg('message', $message);
      $accountObj = $message['params']['account'];
      /** @noinspection PhpSwitchStatementWitSingleBranchInspection */
      switch ($message['key']) {
        case 'password_reset':
          if(!empty($accountObj->field_shared_email['und'][0]['value'])) {
            $message['to'] = $accountObj->field_shared_email['und'][0]['value'];
          }
          break;
      }
      break;
  }
}

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Implements hook_mail
 *
 * @param $key
 * @param $message
 * @param $params
 * @noinspection PhpUnused
 */
function nlpservices_mail($key, &$message, $params) {
 
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {

    case 'deliver_turf':
    case 'account_reminder':
    case 'forward_nl_reply':
      $boundary = uniqid('np');
      $message['headers']['Content-Type'] = 'multipart/alternative; boundary="'. $boundary.'"';
      
      if($key == 'forward_nl_reply') {
        $message['subject'] = $params['subject'];
      } else {
        $message['subject'] = t('Neighborhood Leader Materials - @county County',
          array('@county' => $params['county']), $options);
      }
      
      $message['body'] =  [];
      $msgPlain = "--" . $boundary . "\n";
      $msgPlain .= 'Content-Type: text/plain; charset=UTF-8'."\n";
      $msgPlain .= $params['plainText'];

      $msgHtml = "--" . $boundary . "\n";
      $msgHtml .= "Content-Type: text/html; charset=utf-8\n";
      $msgHtml .= $params['message'];

      $message['body'][0] =  $msgPlain.$msgHtml."\n--" . $boundary . "--";
      break;

    case 'notify bounce':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8;';
      //$message['subject'] = t('Neighborhood Leader Notification - NL email bounce',$options);
      $message['subject'] = t('Neighborhood Leader Notification - NL email bounce');
      $message['body'][] = $params['message'];
      //$message['body'][] = t('<br><em>The NLP services admin sent you this message.</em>');
      break;

  }
}

/**
 * Implements hook_user_login().
 * @noinspection PhpUnused
 */
function nlpservices_user_login(Drupal\user\Entity\User $account)
{
  $user = $account::load(Drupal::currentUser()->id());
  if(empty($user->get('field_county')->getValue()[0]['value'])) {
    return;
  }
  $county = $user->get('field_county')->getValue()[0]['value'];
  //nlp_debug_msg('$county',$county);
  $factory = Drupal::service('tempstore.private');
  $store = $factory->get('nlpservices.session_data');
  $store->set('County',$county);
}

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * implements nlp_debug_msg
 *
 * @param $msg
 * @param mixed $values
 */
function nlp_debug_msg($msg,$values='EMPTY') {
  $messenger = Drupal::messenger();
  $backTrace = debug_backtrace();
  $file = $backTrace[0]['file'];
  $file_path = explode("/", $file);
  $file_name = end($file_path);
  $fnp = str_replace('.php','', $file_name);
  $caller =  str_replace('nlp_','', $fnp);
  $line = $backTrace[0]['line'];
  $location = '@mod @line ';
  $location .= $msg.' = ';

  if(is_string($values) OR is_scalar($values) OR empty($values)) {
    if(!empty($values)) {
      if(is_bool($values)) {
        $msg = t($location.'@values', ['@values' => 'TRUE','@mod'=>$caller,'@line'=>$line]);
      } else {
        $msg = t($location.'@values', ['@values' => $values,'@mod'=>$caller,'@line'=>$line]);
      }
    } elseif($values === 0) {
      $msg = t($location.'@values', ['@values' => '0','@mod'=>$caller,'@line'=>$line]);
    } elseif($values === FALSE) {
      $msg = t($location.'@values', ['@values' => 'FALSE','@mod'=>$caller,'@line'=>$line]);
    } elseif($values === NULL) {
      $msg = t($location.'@values', ['@values' => 'NULL','@mod'=>$caller,'@line'=>$line]);
    } else {
      $msg = t($location.'@values', ['@values' => 'empty','@mod'=>$caller,'@line'=>$line]);
    }
  } elseif (is_object($values)) {
    $huh = print_r(json_encode($values),TRUE);
    $msg = t($location."<br><pre>$huh</pre>",
      ['@mod'=>$caller,'@line'=>$line]);
  } else {
    $nice = highlight_string("<?php\n\$values =\n" . var_export($values, true) . ";\n?>", TRUE);
    $msg = t($location."<br><pre>$nice</pre>",
      ['@mod'=>$caller,'@line'=>$line]);
  }
  $messenger->addMessage($msg, $messenger::TYPE_STATUS,TRUE);
}

/**
 * Implements hook_form_alter().
 * @noinspection PhpUnused
 * @noinspection PhpUnusedParameterInspection
 */
function nlpservices_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  //nlp_debug_msg('$form_id',$form_id);
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  switch ($form_id) {
   
    case 'awake_form':
      $form['#attached']['library'][] = 'nlpservices/info-boxes';
      $form['#attached']['library'][] = 'nlpservices/data-entry-table';
      break;
    case 'nlpservices_sync_active_nls_form':
    case 'nlpservices_manage_drupal_accounts_form':
    case 'nlpservices_login_credentials_reminder_form':
      $form['#attached']['library'][] = 'nlpservices/info-boxes';
    break;
  
    case 'nlpservices_data_entry_form':
      $form['#attached']['library'][] = 'nlpservices/data-entry-table';
      break;
    
    case 'user_register_form':
      $form['#validate'][] = 'nlpservices_add_user_validate';
      break;
  
    case 'user_form':
      $form['#validate'][] = 'nlpservices_user_validate';
      //$form['#submit'][] = 'nlpservices_user_submit';
      $form['actions']['submit']['#submit'][] = 'nlpservices_user_submit';
      break;
  }
}

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * nlpservices_add_user_validate
 *
 * @param $form
 * @param FormStateInterface $form_state
 * @noinspection PhpUnusedParameterInspection
 * @noinspection PhpUnused
 */
function nlpservices_add_user_validate(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  //nlp_debug_msg('$values',$values);
  $response = nlpservices_field_validate($values);
  if($response['status'] ==  'err') {
    $form_state->setErrorByName($response['field'], t($response['msg']));
  }
}

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * nlpservices_user_validate
 *
 * @param $form
 * @param FormStateInterface $form_state
 * @return void
 * @noinspection PhpUnusedParameterInspection
 * @noinspection PhpUnused
 */
function nlpservices_user_validate(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $response = nlpservices_field_validate($values);
  if($response['status'] ==  'err') {
    $form_state->setErrorByName($response['field'], t($response['msg']));
  }
}

/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * nlpservices_field_validate
 *
 * @param $values
 * @return array
 */
function nlpservices_field_validate($values): array
{
  $mcid = (empty($values['field_mcid'][0]['value'])) ? NULL: $values['field_mcid'][0]['value'];
  $county = (empty($values['field_county'][0]['value'])) ? NULL: $values['field_county'][0]['value'];
  
  $config = Drupal::getContainer()->get('config.factory');
  $nlpConfig = $config->get('nlpservices.configuration');
  $countyNames = $nlpConfig->get('nlpservices-county-names');
  $countyNames = array_keys($countyNames);
  unset($countyNames[0]);
  if(!empty($county) AND !in_array($county,$countyNames)) {
    return [
      'status' => 'err',
      'msg' => 'Unknown county, check spelling.',
      'field' => 'field_county'
    ];
  }
  
  $roles = $values['roles'];
  if(in_array(NLP_LEADER_ROLE_ID,$roles)) {
    if(empty($mcid)) {
      return [
        'status' => 'err',
        'msg' => 'You must specify an MCID for an NLP Leader.',
        'field' => 'field_mcid'
      ];
    }
    if(empty($county)) {
      return [
        'status' => 'err',
        'msg' => 'You must specify a County for an NLP Leader.',
        'field' => 'field_county'
      ];
    }
    
  }
  if(in_array(NLP_COORDINATOR_ROLE_ID,$roles)) {
    if(empty($values['field_county'][0]['value'])) {
      return [
        'status' => 'err',
        'msg' => 'You must specify a County for an NLP Coordinator.',
        'field' => 'field_county'
      ];
    }
  }
  return ['status' => 'ok',];
}


/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * nlpservices_user_submit
 *
 * @param $form
 * @param FormStateInterface $form_state
 * @return void
 * @noinspection PhpUnused
 * @noinspection PhpUnusedParameterInspection
 */
function nlpservices_user_submit(&$form, FormStateInterface $form_state) {
  //$values = $form_state->getValues();
  //nlp_debug_msg('$values',$values);
  $mcidValue = $form_state->getValue('field_mcid');
  //nlp_debug_msg('$mcidValue',$mcidValue);
  if(!empty($mcidValue[0]['value'])) {
    $mcid = $mcidValue[0]['value'];
    //nlp_debug_msg('$mcid',$mcid);
    $pass = $form_state->getValue('pass');
    //nlp_debug_msg('submit - $pass',$pass);
    if(!empty($pass)) {
      $magicWordObj = Drupal::getContainer()->get('nlpservices.magic_word');
      $magicWord = $magicWordObj->getMagicWord($mcid);
      //nlp_debug_msg('$magicWord',$magicWord);
      if($magicWord != $pass) {
        $magicWordObj->setMagicWord($mcid,$pass);
      }
    }
  }
}


/** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * This converts a string to hex for debugging
 *
 * @param $string
 * @return string
 * @noinspection PhpUnused
 */
function strToHex($string): string
{
  $hex = '';
  for ($i = 0; $i < strlen($string); $i++) {
    $so = ord($string[$i]);
    $sh = dechex($so);
    $shp = str_pad($sh, 2, '0',STR_PAD_LEFT);
    if(($so < 128) AND ($so > 31)) {
      $hex .= ' '.$string[$i].' '.$shp;
    } else {
      $hex .= ' .. '.$shp;
    }
    if($i>255) {break;}
  }
  return $hex;
}


